# Generated by Django 6.0.1 on 2026-03-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogcomment_created_at_blogcomment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
